In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
data = pd.read_csv('USA_Housing.csv')

In [20]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [21]:
data.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [22]:
data_pd = pd.DataFrame(data)

In [23]:
data_pd.columns = ['income','age','#rooms','#bedrooms','population','price','address']

In [28]:
data = data_pd

In [30]:
y = data['price']

In [31]:
x = data[['income','age','#rooms','#bedrooms','population']]

In [32]:
y = np.array(y)

In [35]:
n = data.shape[0]
n # no. of data

5000

In [36]:
x_bias = np.ones((n,1))
x_new = x_bias

In [37]:
for(columnName, columnData) in x.iteritems():
    temparr = np.array(columnData)
    tempNew = temparr.reshape(-1,1)
    x_new = np.append(x_new, tempNew, axis=1)

In [38]:
x_new

array([[1.00000000e+00, 7.95454586e+04, 5.68286132e+00, 7.00918814e+00,
        4.09000000e+00, 2.30868005e+04],
       [1.00000000e+00, 7.92486425e+04, 6.00289981e+00, 6.73082102e+00,
        3.09000000e+00, 4.01730722e+04],
       [1.00000000e+00, 6.12870672e+04, 5.86588984e+00, 8.51272743e+00,
        5.13000000e+00, 3.68821594e+04],
       ...,
       [1.00000000e+00, 6.33906869e+04, 7.25059061e+00, 4.80508098e+00,
        2.13000000e+00, 3.32661455e+04],
       [1.00000000e+00, 6.80013312e+04, 5.53438842e+00, 7.13014386e+00,
        5.44000000e+00, 4.26256202e+04],
       [1.00000000e+00, 6.55105818e+04, 5.99230531e+00, 6.79233610e+00,
        4.07000000e+00, 4.65012838e+04]])

In [41]:
x_new_transpose = x_new.T

In [42]:
x_new_transpose_dot_x_new = np.dot(x_new_transpose,x_new)

In [43]:
# finding inverse of the matrix
temp1 = np.linalg.inv(x_new_transpose_dot_x_new)
temp1

array([[ 2.87715060e-02, -1.23722508e-07, -1.24739801e-03,
        -1.42122305e-03,  2.65227913e-05, -7.75544612e-08],
       [-1.23722508e-07,  1.76306802e-12,  5.17513617e-11,
         4.76128750e-10, -4.75851029e-10,  2.94198179e-14],
       [-1.24739801e-03,  5.17513617e-11,  2.03619869e-04,
         3.09050121e-06, -2.11314129e-06,  3.75652347e-10],
       [-1.42122305e-03,  4.76128750e-10,  3.09050121e-06,
         2.51811650e-04, -9.51084550e-05, -3.00114739e-10],
       [ 2.65227913e-05, -4.75851029e-10, -2.11314129e-06,
        -9.51084550e-05,  1.67378640e-04,  4.68752910e-10],
       [-7.75544612e-08,  2.94198179e-14,  3.75652347e-10,
        -3.00114739e-10,  4.68752910e-10,  2.03305122e-12]])

In [44]:
# finding the dot product of x and y
temp2 = np.dot(x_new_transpose,y)
temp2

array([6.16036327e+09, 4.34532727e+14, 3.76138778e+10, 4.36433193e+10,
       2.48991246e+10, 2.29938746e+14])

In [45]:
# finding coefficients
theta = np.dot(temp1, temp2)
theta

array([-2.63729903e+06,  2.15780494e+01,  1.65637027e+05,  1.20659949e+05,
        1.65113905e+03,  1.52007439e+01])

In [48]:
def predict_values(theta, test_data):
    y = []
    for i in test_data.index:
        y.append(theta[0])
        for idx, column in enumerate(test_data.columns):
            y[i] = y[i] + theta[idx+1]*test_data[column][i]
    return y

In [49]:
xyz = data[['income','age','#rooms','#bedrooms','population']]
predicted_y = predict_values(theta,xyz)

In [50]:
error = y - predicted_y
absolute_error = np.sum(error)
mean_absolute_error = absolute_error/n
se = np.sum(error**2)
mse = se/n

In [52]:
# mean absolute error
mean_absolute_error

4.259124398231506e-09

In [53]:
# mean squared error
mse

10219734313.253004

In [55]:
# root mean squared error
np.sqrt(mse)

101092.70158252279